import { Inter } from 'next/font/google'
import { ThemeProvider } from "@/components/theme-provider";
import Theme from '@/components/Theme';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
       
          
          {children}
          <footer></footer>

      </body>
    </html>
  )
}